### ISSUE TITLE
Would it be possible to only download trips in a folder?

### ISSUE THREAD

**Issue by jbbenac** [samueldumont/cowboybike-strava-sync#1]
In case I would like to use other service than Strava.

**Comment by samueldumont** [comment]
Ah yes good idea ! Would you still want a TCX output ? With that, you should be able to upload to almost any service.

Also, to which service would you like to upload ? It could be an option to upload to multiple destinations

**Comment by jbbenac** [comment]
I was thinking about Runtastic maybe, but I’d like to keep TCX files in a folder to archive.

**Comment by samueldumont** [comment]
Hi @jbbenac,

I added two options, one is `TCX_EXPORT_DIRECTORY`, the destination for your TCX files. The other is `UPLOAD_TO_STRAVA`. If you set it to "False" (or anything else than True) it will disable the upload to Strava.

Unfortunately, Runtastic does not provide an API so it won't be possible to automatically upload the files, sorry !
